apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: nltstg-argo-application
    namespace: argocd
spec:
    project: default

    source:
        repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
        targetRevision: HEAD
        path: stg
    destination:
        server: https://kubernetes.default.svc
        namespace: nltstg

    syncPolicy:
        syncOptions:
            - CreateNamespace=true

        automated:
            selfHeal: true
            prune: true
